name: famitsu-data-actions
on:
  workflow_dispatch:
  push:
    branches: [main]
  #schedule:
    #- cron: '*/60 * * * *' #the schedule, in this case every 30 mins, in cron time (URL CRON)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: checkout code
         uses: actions/checkout@v2
       - name: setup python
         uses: actions/setup-python@v2
         with:
          python-version: '3.7.7' # install the python version needed
          
       - name: install python packages
         run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          
       - name: execute py script
         run: python3 main.py #NAME OF YOUR FILE HERE!!
      
    
      
       - name: commit files

         run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a || echo "No changes to commit"
          
       - name: push changes
         uses: ad-m/github-push-action@v0.6.0
         with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
